Artifactory:
  server: mjswampup2021.jfrog.io
  intName: swampupArtifactory
  devRepo: swampup-docker-local
  prodRepo: swampup-docker-prod-local
  creds: awsEcsDockerComposePullSecrets
GitHub:
  path: mjmckay/gs-spring-boot-docker
  gitProvider: swampupConfig
Shipa:
  intName: mjmckayShipa
app:
  dockerImageName: mjswampup2021.jfrog.io/swampup-docker-local/gs-spring-boot-docker
  dockerFileLocation: complete
  dockerFileName: Dockerfile
  buildName: swampup-shipa-gs-spring-boot-docker
